name = "todo-app"
main = "worker.js"
compatibility_date = "2023-12-01"

[[d1_databases]]
binding = "DB"
database_name = "todo-app-db"
database_id = "your-database-id"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "todo-app-db"
database_id = "your-database-id"

[env.staging]
[[env.staging.d1_databases]]
binding = "DB"
database_name = "todo-app-db-staging"
database_id = "your-staging-database-id"